CCCCCCCCCCCCCCcCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C     getdata.f
C
C     A LIBRARY OF FUNCTIONS AND SUBROUTINES THAT OBTAINS FROM THE
C     USER INFORMATION ABOUT THE SELECTED ION NEEDED FOR THE NRADIUS
C     PACKAGE.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC


      SUBROUTINE GETION(ZE, R)
C     THIS SUBROUTINE OBTAINS THE 

      DOUBLE PRECISION R, ZE
      
      WRITE(6,*) 'ENTER Ze, Charge Radius (in fermi''s) ...'                                
      READ(5,*) ZE,R

      IF(ZE.GT.0) ZE = -ZE

      END

      
      SUBROUTINE STATES(N1,N2,KAPPA1,KAPPA2)

      INTEGER KAPPA1, KAPPA2, N1, N2
      
      WRITE(6,*) '   ENTER N1, K1 ...'
      READ(5,*) N1, KAPPA1
      WRITE(6,*) '   ENTER N2, K2 ...'
      READ(5,*) N2, KAPPA2

      END
