      BLOCK DATA MCONST
C     MATHEMATICAL CONSTANTS
      DOUBLE PRECISION PI
      COMMON /MCON/ PI 
      DATA PI /ACOS(-1D0)/
      END

      BLOCK DATA PCONST
C     PHYSICAL CONSTANTS
      DOUBLE PRECISION BOHR
      COMMON /PCON/ BOHR HEV
      DATA BOHR /5.2917721092D-11/
      DATA HEV  /2.721138D1/ 
      END
